"""Bundle our observation-only SQP agent into one reproducible source file.

Only our controller math is included. No replay, cache, seed schedule or
simulator implementation is embedded. The official BaseAgent stays imported.
"""

import ast
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AGENTS = ROOT / 'BalloonPoppingGymEnv/agents'
OUTPUT = AGENTS / 'submission_sqp_v2.py'


def selected_source(filename, names=None):
    source = (AGENTS / filename).read_text(encoding='utf-8')
    tree = ast.parse(source)
    selected = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue
        if names is not None and getattr(node, 'name', None) not in names:
            continue
        selected.append(ast.unparse(node))
    return '\n\n'.join(selected)


def main():
    header = '''"""Submission SQP v2: observation-only receding-horizon guidance.

Generated by scripts/build_submission_agent.py from our controller sources.
Uses given_parameters, observation history and numerical optimization only.
No file/network I/O, replay tables, simulator state access, or seed lookup.
"""
from functools import lru_cache

import numpy as np
from scipy.optimize import minimize

from BalloonPoppingGymEnv.agents.base_agent import BaseAgent


def get_initial_attitude(inclination, heading):
    """Quaternion from the commanded launch angles (zero initial bank)."""
    theta = np.radians(inclination - 90.0) / 2.0
    psi = np.radians(-heading) / 2.0
    return np.array([np.cos(theta)*np.cos(psi),
                     np.sin(theta)*np.cos(psi),
                     np.sin(theta)*np.sin(psi),
                     np.cos(theta)*np.sin(psi)])
'''
    chunks = [header]
    chunks.append(selected_source('multi_target_agent.py', {
        '_multiply_quaternions', '_rotate_body_to_world', '_rotate_world_to_body',
    }))
    chunks.append(selected_source('physics_guidance_agent.py'))
    chunks.append(selected_source('spline_route_agent.py'))
    chunks.append(selected_source('beam_intercept_agent.py', {'batch_samples'}))
    tree = ast.parse((AGENTS / 'joint_beam_agent.py').read_text(encoding='utf-8'))
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef))
    cls.name = 'RouteOptimizerMixin'
    cls.bases = []
    cls.body = [n for n in cls.body if isinstance(n, ast.FunctionDef)
                and n.name in {'_curves', '_margins', '_solve'}]
    chunks.append(ast.unparse(cls))
    optimized = selected_source('optimized_spline_agent.py')
    chunks.append(optimized.replace('JointBeamAgent.', 'RouteOptimizerMixin.'))
    chunks.append('class SubmissionAgent(OptimizedSplineAgent):\n'
                  '    """Public entry point for the official evaluator."""\n')
    source = '\n\n\n'.join(chunks) + '\n'
    compile(source, str(OUTPUT), 'exec')
    OUTPUT.write_text(source, encoding='utf-8', newline='\n')
    print(f'{OUTPUT}\nsha256={hashlib.sha256(source.encode()).hexdigest()}')


if __name__ == '__main__':
    main()
